Traceback (most recent call last):
  File "/project2/tas1/pragallva/Summer_quarter_2018//codes/python_scripts/Extract_ncfile_save_fluxes_radiation_depths.py", line 52, in <module>
    v_variables = nc.Dataset(one_year,'r')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13227)
IOError: No such file or directory
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Summer_quarter_2018//codes/python_scripts/Extract_ncfile_save_fluxes_radiation_depths.py", line 52, in <module>
    v_variables = nc.Dataset(one_year,'r')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13227)
IOError: No such file or directory
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Summer_quarter_2018//codes/python_scripts/Extract_ncfile_save_fluxes_radiation_depths.py", line 52, in <module>
    v_variables = nc.Dataset(one_year,'r')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13227)
IOError: No such file or directory
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Summer_quarter_2018//codes/python_scripts/Extract_ncfile_save_fluxes_radiation_depths.py", line 52, in <module>
    v_variables = nc.Dataset(one_year,'r')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13227)
IOError: No such file or directory
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Summer_quarter_2018//codes/python_scripts/Extract_ncfile_save_fluxes_radiation_depths.py", line 52, in <module>
    v_variables = nc.Dataset(one_year,'r')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13227)
IOError: No such file or directory
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Summer_quarter_2018//codes/python_scripts/Reload_save_interpolated_depths.py", line 112, in <module>
    decomposed_fluxes.append(load(source+"zonal_decomposed_fluxes_dic.hkl"))
  File "/project2/tas1/pragallva/Summer_quarter_2018//codes/python_scripts/Reload_save_interpolated_depths.py", line 31, in load
    dictionary = hkl.load(filename)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/hickle/hickle.py", line 491, in load
    with file_opener(fileobj) as h5f:
  File "/home/pragallva/Project1/lib/python2.7/site-packages/hickle/hickle.py", line 173, in file_opener
    h5f = h5.File(filename, mode)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-install-6ALcG4/h5py/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-install-6ALcG4/h5py/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-install-6ALcG4/h5py/h5py/h5f.c:2120)
IOError: Unable to open file (unable to open file: name = '/project2/tas1/pragallva/Summer_quarter_2018/post_process_data/aqua_isca_50m_0.050/zonal_decomposed_fluxes_dic.hkl', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
