Traceback (most recent call last):
  File "/project2/tas1/pragallva/Winter_quarter_2019//codes/python_scripts/isca/Reload_save_synoptic_variability.py", line 96, in <module>
    momentum_fluxes.append(load(source+"eddies_"+FREQ+'_freq_'+'avg'+str(days)+'.hkl'))
  File "/project2/tas1/pragallva/Winter_quarter_2019//codes/python_scripts/isca/Reload_save_synoptic_variability.py", line 38, in load
    dictionary = hkl.load(filename)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/hickle/hickle.py", line 491, in load
    with file_opener(fileobj) as h5f:
  File "/home/pragallva/Project1/lib/python2.7/site-packages/hickle/hickle.py", line 173, in file_opener
    h5f = h5.File(filename, mode)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-install-6ALcG4/h5py/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-install-6ALcG4/h5py/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-install-6ALcG4/h5py/h5py/h5f.c:2120)
IOError: Unable to open file (unable to open file: name = '/project2/tas1/pragallva/Fall_quarter_2018//post_process_data/synoptic/HC0_la50m_oc50m0/eddies_monthly_pass_freq_avg30.hkl', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
